<?php /** @var $this \MvcCore\View */ ?>

<h1><?php echo $this->Title; ?></h1>

<p>You are running MvcCore framework basic example how to build your MVC app.</p>

<p>MvcCore version: <code><b>&quot;<?php echo $this->Version; ?>&quot;</b></code></p>

<p>
	Compile mode: <code><b>&quot;<?php echo $this->CompileMode; ?>&quot;</b></code><br />
    <?php if ($this->CompileMode == ''): ?>
		<small><i>Mode is empty string - you are in development environment.</i></small>
    <?php elseif ($this->CompileMode == 'SFU'): ?>
		<small><i>Single File Mode - to generate all assets in <code><b>/Var/Tmp</b></code> directory.</i></small>
    <?php elseif (strpos($this->CompileMode, 'PHP') === 0): ?>
    <small><i>Application is packed as single PHP file.</i></small>
    <?php elseif (strpos($this->CompileMode, 'PHAR') === 0): ?>
		<small><i>Application is packed as standard PHAR archive.</i></small>
	<?php endif; ?>
</p>

<h2>Compilation process:</h2>
<ol>
	<li>
		Clear everything in <b><code>/Var/Tmp</code></b> directory.
	</li>
	<li>
		Add <b><code>TRUE</code></b> param into <b><code>index.php</code></b>: <br />
		<b><code>\MvcCore::GetInstance()->Run(1);</code></b> <br />
		to&nbsp;temporary switch application compile <br />mode to&nbsp;<b>SFU</b> (Single File Url mode).
	</li>
	<li>
		Visit all application routes where are different CSS or JS assets groups to complete
		all possible asset files in <b><code>/Var/Tmp</code></b> directory. Process those requests
		on addresses with the same or empty request base path as result application will have.
	</li>
	<li>
		Run <b><code>/make-php.php</code></b> script in browser or in CLI to build result application.
		Do not include any PHP autoloaders, any unnecessary code you don't need and any source CSS/JS
		files are not necessary.
	</li>
	<li>
		Visit your application in <b><code>/release</code></b> directory and enjoy result.
	</li>
</ol>